services:
  # Base de Datos Relacional MySQL 8.0
  db:
    image: mysql:8.0
    container_name: inventario-mysql
    restart: always
    environment:
      MYSQL_DATABASE: inventario_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicación Web Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventario-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/inventario_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: ClaveSecretaSuperSeguraParaFirmarTokensJWTInventarioSucursalesMexico2026DebeTenerMasDe256Bits
      PORT: 8080
    ports:
      - "8080:8080"

  # SonarQube Community Build (para análisis estático de código local )
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: unless-stopped
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  mysql_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
